/// Flutter icons AppBarIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppBarIcon
///      fonts:
///       - asset: fonts/AppBarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppBarIcon {
  AppBarIcon._();

  static const _kFontFam = 'AppBarIcon';

  static const IconData logo = IconData(0xe800, fontFamily: _kFontFam);
}
